# Generated by Django 6.0.6 on 2026-06-23 21:43

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ManualAccessToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("revoked", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lafre_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PasswordResetToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lafre_password_reset_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("citizen", "Citizen / Public User"),
                            ("student", "Student"),
                            ("lawyer", "Lawyer"),
                            ("admin", "Admin"),
                        ],
                        default="citizen",
                        max_length=30,
                    ),
                ),
                (
                    "requested_role",
                    models.CharField(
                        choices=[
                            ("citizen", "Citizen / Public User"),
                            ("student", "Student"),
                            ("lawyer", "Lawyer"),
                            ("admin", "Admin"),
                        ],
                        default="citizen",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending approval"),
                            ("approved", "Approved"),
                            ("suspended", "Suspended"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=60)),
                ("city", models.CharField(blank=True, max_length=80)),
                ("access_reason", models.TextField(blank=True)),
                ("institution", models.CharField(blank=True, max_length=180)),
                ("student_number", models.CharField(blank=True, max_length=80)),
                ("organisation", models.CharField(blank=True, max_length=180)),
                ("practice_area", models.CharField(blank=True, max_length=180)),
                (
                    "auth_provider",
                    models.CharField(
                        choices=[("email", "Email/password"), ("google", "Google")],
                        default="email",
                        max_length=30,
                    ),
                ),
                (
                    "google_sub",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("email_verified", models.BooleanField(default=False)),
                ("can_use_civilian", models.BooleanField(default=True)),
                ("can_use_student", models.BooleanField(default=False)),
                ("can_generate_documents", models.BooleanField(default=False)),
                ("can_submit_review", models.BooleanField(default=False)),
                ("can_request_lawyer", models.BooleanField(default=False)),
                ("can_access_lawyer_portal", models.BooleanField(default=False)),
                ("can_access_admin", models.BooleanField(default=False)),
                ("can_upload_assignments", models.BooleanField(default=False)),
                ("can_use_assignment_help", models.BooleanField(default=False)),
                ("daily_message_limit", models.PositiveIntegerField(default=0)),
                ("monthly_message_limit", models.PositiveIntegerField(default=0)),
                ("daily_document_limit", models.PositiveIntegerField(default=0)),
                ("monthly_document_limit", models.PositiveIntegerField(default=0)),
                ("daily_upload_limit", models.PositiveIntegerField(default=0)),
                ("monthly_upload_limit", models.PositiveIntegerField(default=0)),
                ("messages_used_today", models.PositiveIntegerField(default=0)),
                ("documents_used_today", models.PositiveIntegerField(default=0)),
                ("uploads_used_today", models.PositiveIntegerField(default=0)),
                ("monthly_messages_used", models.PositiveIntegerField(default=0)),
                ("monthly_documents_used", models.PositiveIntegerField(default=0)),
                ("monthly_uploads_used", models.PositiveIntegerField(default=0)),
                ("usage_day", models.DateField(default=datetime.date.today)),
                ("usage_month", models.CharField(default="", max_length=7)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("account_expiry", models.DateField(blank=True, null=True)),
                ("admin_notes", models.TextField(blank=True)),
                (
                    "theme_preference",
                    models.CharField(
                        choices=[
                            ("light", "Light"),
                            ("dark", "Dark"),
                            ("system", "System"),
                        ],
                        default="system",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_lafre_users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lafre_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
