# Generated by Django 6.1.1 on 2026-09-08 03:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('color', models.CharField(default='#8a887f', help_text='Hex color, e.g. #f97316', max_length=7)),
                ('description', models.CharField(blank=True, max_length=280)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'communities',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LawyerBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('icon', models.CharField(default='★', help_text='Emoji or short glyph shown next to the badge', max_length=10)),
                ('color', models.CharField(default='#d99a2b', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='LawyerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('firm_name', models.CharField(blank=True, max_length=180)),
                ('practice_area', models.CharField(blank=True, max_length=120)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('years_experience', models.PositiveSmallIntegerField(default=0)),
                ('bio', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('public_email', models.EmailField(blank=True, max_length=254)),
                ('verified', models.BooleanField(default=False, help_text='Only verified lawyers show the ★★★ badge anywhere in the app')),
                ('mentorship_available', models.BooleanField(default=False)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('badges', models.ManyToManyField(blank=True, related_name='lawyers', to='forum.lawyerbadge')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forum_lawyer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-rating'],
            },
        ),
        migrations.CreateModel(
            name='FindLawyerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('location_text', models.CharField(blank=True, max_length=180)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lawyer_requests', to=settings.AUTH_USER_MODEL)),
                ('matched_lawyers', models.ManyToManyField(blank=True, related_name='matched_requests', to='forum.lawyerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='LawyerPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('sponsored', 'Sponsored'), ('featured', 'Featured')], max_length=20)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='forum.lawyerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='MentorshipProgramme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('area', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('topics', models.JSONField(blank=True, default=list, help_text='List of short strings describing what students will learn')),
                ('weeks', models.PositiveSmallIntegerField(default=4)),
                ('is_free', models.BooleanField(default=True)),
                ('fee_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorship_programmes', to='forum.lawyerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MentorshipMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorship_messages', to=settings.AUTH_USER_MODEL)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='forum.mentorshipprogramme')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MentorshipMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file_url', models.URLField(blank=True)),
                ('material_type', models.CharField(default='Link', help_text='e.g. PDF, DOCX, Link', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='forum.mentorshipprogramme')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_role', models.CharField(choices=[('civilian', 'Civilian'), ('student', 'Law student'), ('lawyer', 'Lawyer')], max_length=20)),
                ('title', models.CharField(max_length=220)),
                ('text', models.TextField()),
                ('language', models.CharField(default='en', help_text="Best-effort detected language code, e.g. 'en', 'sn' (Shona)", max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_posts', to=settings.AUTH_USER_MODEL)),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='forum.community')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LawyerEngagementEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('forum_reply', 'Replied to a forum post'), ('helpful_mark', 'Marked helpful by a user'), ('profile_view', 'Profile viewed'), ('mentorship_session', 'Ran a mentorship session')], max_length=30)),
                ('points', models.DecimalField(decimal_places=2, default=4.5, help_text='Contribution to the rolling rating average for this event', max_digits=3)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_events', to='forum.lawyerprofile')),
                ('related_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.post')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_role', models.CharField(blank=True, max_length=20)),
                ('text', models.TextField()),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forum_comments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='forum.post')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MentorshipEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorship_enrollments', to=settings.AUTH_USER_MODEL)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='forum.mentorshipprogramme')),
            ],
            options={
                'unique_together': {('programme', 'student')},
            },
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='forum.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('post', 'user')},
            },
        ),
        migrations.CreateModel(
            name='SavedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='forum.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_saved_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('post', 'user')},
            },
        ),
    ]
