'use client';
import {useState} from 'react';
import Link from 'next/link';
import LafreShell from '../prototype/components/LafreShell';
import {requests} from '../prototype/mock-api';
import Status from '../prototype/components/Status';
import ui from '../prototype/components/ui.module.css';
export default function LegalHelp(){
 const [sent,setSent]=useState(false); return <LafreShell active="Legal Help Requests"><div className={ui.shell}><div className={ui.row}><div><div className={ui.eyebrow}>Private professional connection</div><h1 className={ui.title}>Legal help requests</h1><p className={ui.subtitle}>This area demonstrates how a civilian moves from a public question to a structured request for professional assistance.</p></div><Status/></div>
 <div className={ui.twoCol} style={{marginTop:22}}><section className={ui.panel+' '+ui.pad}><h2 style={{fontSize:20,marginTop:0}}>Create a request</h2><p className={ui.muted} style={{fontSize:13}}>In the real app this would become a backend record visible to suitable verified lawyers.</p><div style={{display:'grid',gap:11}}><input placeholder="Short title" style={{height:42,border:'1px solid #d8d4cb',borderRadius:7,padding:'0 12px'}}/><select style={{height:42,border:'1px solid #d8d4cb',borderRadius:7,padding:'0 12px'}}><option>Area of law</option><option>Employment Law</option><option>Property Law</option><option>Contracts</option><option>Family Law</option></select><input placeholder="Location / jurisdiction" style={{height:42,border:'1px solid #d8d4cb',borderRadius:7,padding:'0 12px'}}/><textarea placeholder="Describe the problem without publishing unnecessary sensitive information..." style={{minHeight:150,border:'1px solid #d8d4cb',borderRadius:7,padding:12}}/><select style={{height:42,border:'1px solid #d8d4cb',borderRadius:7,padding:'0 12px'}}><option>Preferred contact method</option><option>LAFRE messaging</option><option>Phone</option><option>Email</option></select><button className={ui.goldBtn} onClick={()=>setSent(true)}>{sent?'Mock API: request created':'Submit legal-help request'}</button></div></section>
 <aside><div className={ui.panel+' '+ui.pad}><div className={ui.eyebrow}>How it works</div>{['Civilian creates request','Suitable lawyers see relevant requests','Lawyer expresses interest','Civilian reviews profile','Private communication begins'].map((x,i)=><div key={x} className={ui.listItem}><b>{i+1}. {x}</b></div>)}<p className={ui.muted} style={{fontSize:11}}>No payment or legal representation is simulated here.</p></div></aside></div>
 <section style={{marginTop:24}}><div className={ui.row}><h2 style={{fontSize:21}}>Open requests <span className={ui.muted} style={{fontSize:12}}>(lawyer preview)</span></h2><span className={ui.muted} style={{fontSize:12}}>Mock records</span></div><div className={ui.panel}>{requests.map(r=><div key={r.id} className={ui.post}><div className={ui.row}><div><span className={ui.tag}>{r.area}</span><div className={ui.postTitle}>{r.title}</div><div className={ui.postExcerpt}>{r.summary}</div></div><Link href="/lawyers" className={ui.outlineBtn}>See matching lawyers</Link></div><div className={ui.metrics} style={{marginTop:9}}><span>{r.location}</span><span>{r.matches} potential matches</span><span>{r.posted}</span></div></div>)}</div></section>
 </div></LafreShell>
}
