# Generated by Django 6.0.6 on 2026-06-23 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeBaseNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("body", models.TextField()),
                ("tags", models.JSONField(blank=True, default=list)),
                ("matter_type", models.CharField(blank=True, max_length=80)),
                ("topic", models.CharField(blank=True, max_length=120)),
                ("verified", models.BooleanField(default=True)),
                ("visible_to_citizen", models.BooleanField(default=True)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["matter_type", "topic", "title"],
            },
        ),
        migrations.CreateModel(
            name="LawyerBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                ("description", models.TextField(blank=True)),
                ("assigned_by_admin_only", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PlatformSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.SlugField(max_length=80, unique=True)),
                ("label", models.CharField(max_length=160)),
                ("value", models.TextField(blank=True)),
                ("is_public", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="PublicAnnouncement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=140)),
                ("body", models.TextField()),
                ("cta_label", models.CharField(blank=True, max_length=60)),
                ("cta_url", models.CharField(blank=True, max_length=255)),
                ("active", models.BooleanField(default=True)),
                ("collapsible", models.BooleanField(default=True)),
                ("priority", models.CharField(default="normal", max_length=20)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["sort_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PublicMatterType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100, unique=True)),
                ("letter", models.CharField(blank=True, max_length=8)),
                ("group", models.CharField(blank=True, max_length=80)),
                ("title", models.CharField(max_length=120)),
                ("short_description", models.CharField(blank=True, max_length=220)),
                ("detailed_description", models.TextField(blank=True)),
                ("background_routing_prompt", models.TextField(blank=True)),
                ("kb_terms", models.JSONField(blank=True, default=list)),
                ("intake_questions", models.JSONField(blank=True, default=list)),
                ("urgency_keywords", models.JSONField(blank=True, default=list)),
                ("requires_location", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["sort_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="AdminNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("message", models.TextField(blank=True)),
                ("type", models.CharField(default="general", max_length=80)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("related_object_type", models.CharField(blank=True, max_length=80)),
                (
                    "related_object_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "related_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lafre_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CitizenMatter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "matter_type",
                    models.CharField(default="lending_money", max_length=80),
                ),
                ("title", models.CharField(max_length=220)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_signature", "Pending signature"),
                            ("awaiting_proofs", "Awaiting proofs"),
                            ("active_repayment", "Active repayment"),
                            ("review_requested", "Review requested"),
                            ("assigned_to_lawyer", "Assigned to lawyer"),
                            ("in_review", "In review"),
                            ("changes_requested", "Changes requested"),
                            ("reviewed", "Reviewed"),
                            ("overdue", "Overdue"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        default="pending_signature",
                        max_length=40,
                    ),
                ),
                ("intake_json", models.JSONField(blank=True, default=dict)),
                ("validation_json", models.JSONField(blank=True, default=dict)),
                ("kb_support_json", models.JSONField(blank=True, default=dict)),
                ("smart_summary_json", models.JSONField(blank=True, default=dict)),
                ("generated_document_text", models.TextField(blank=True)),
                (
                    "document_file",
                    models.FileField(
                        blank=True, null=True, upload_to="citizen_generated/%Y/%m/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="citizen_matters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="GeneratedDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document_type", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=180)),
                ("content", models.TextField()),
                ("template_source_note", models.CharField(blank=True, max_length=255)),
                ("status", models.CharField(default="draft", max_length=40)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeBaseFailure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_issue", models.TextField()),
                ("search_query", models.TextField(blank=True)),
                ("knowledge_base_id", models.CharField(blank=True, max_length=80)),
                ("region", models.CharField(blank=True, max_length=60)),
                ("source_count", models.PositiveIntegerField(default=0)),
                ("action_needed", models.CharField(blank=True, max_length=180)),
                ("resolved", models.BooleanField(default=False)),
                ("admin_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kb_failures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Lawyer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=160)),
                ("firm_name", models.CharField(blank=True, max_length=180)),
                ("slug", models.SlugField(max_length=220, unique=True)),
                ("practice_areas", models.JSONField(blank=True, default=list)),
                ("services", models.JSONField(blank=True, default=list)),
                ("languages", models.JSONField(blank=True, default=list)),
                ("city", models.CharField(blank=True, max_length=80)),
                ("province", models.CharField(blank=True, max_length=80)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("website", models.URLField(blank=True)),
                ("years_experience", models.PositiveSmallIntegerField(default=0)),
                (
                    "consultation_mode",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("in_person", "In person"),
                            ("both", "Online and in person"),
                        ],
                        default="online",
                        max_length=20,
                    ),
                ),
                (
                    "consultation_fee_usd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("accepts_free_legal_aid", models.BooleanField(default=False)),
                ("available_for_appointments", models.BooleanField(default=True)),
                ("verified", models.BooleanField(default=False)),
                ("verification_note", models.CharField(blank=True, max_length=255)),
                ("verification_documents", models.JSONField(blank=True, default=list)),
                ("bio", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lawyer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "badges",
                    models.ManyToManyField(
                        blank=True, related_name="lawyers", to="civilian.lawyerbadge"
                    ),
                ),
            ],
            options={
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="DocumentReviewRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review_type", models.CharField(default="review_only", max_length=30)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("waiting_assignment", "Waiting assignment"),
                            ("assigned", "Assigned"),
                            ("in_review", "In review"),
                            ("changes_requested", "Changes requested"),
                            ("reviewed", "Reviewed"),
                            ("completed", "Completed"),
                        ],
                        default="requested",
                        max_length=40,
                    ),
                ),
                ("user_note", models.TextField(blank=True)),
                ("admin_note", models.TextField(blank=True)),
                ("lawyer_note", models.TextField(blank=True)),
                (
                    "reviewed_file",
                    models.FileField(
                        blank=True, null=True, upload_to="lawyer_reviewed/%Y/%m/"
                    ),
                ),
                (
                    "signed_or_stamped_file",
                    models.FileField(
                        blank=True, null=True, upload_to="lawyer_signed/%Y/%m/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="review_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_requests",
                        to="civilian.generateddocument",
                    ),
                ),
                (
                    "assigned_lawyer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_reviews",
                        to="civilian.lawyer",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="LegalMatter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("pathway_id", models.CharField(blank=True, max_length=100)),
                ("issue_type", models.CharField(blank=True, max_length=80)),
                ("city", models.CharField(blank=True, max_length=80)),
                ("description", models.TextField(blank=True)),
                ("support_route", models.CharField(blank=True, max_length=80)),
                ("urgency", models.CharField(default="normal", max_length=30)),
                ("answers_json", models.JSONField(blank=True, default=dict)),
                ("guidance_json", models.JSONField(blank=True, default=dict)),
                ("source_count", models.PositiveIntegerField(default=0)),
                ("grounding_status", models.CharField(blank=True, max_length=60)),
                ("status", models.CharField(default="open", max_length=40)),
                ("admin_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="legal_matters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="LegacyMatterAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(default="other", max_length=60)),
                ("title", models.CharField(blank=True, max_length=180)),
                ("file", models.FileField(upload_to="matter_attachments/%Y/%m/")),
                ("note", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="legacy_matter_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "matter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="legacy_attachments",
                        to="civilian.legalmatter",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="LawyerAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(default="assigned", max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lawyer_assignments_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document_review",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assignments",
                        to="civilian.documentreviewrequest",
                    ),
                ),
                (
                    "lawyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="civilian.lawyer",
                    ),
                ),
                (
                    "matter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assignments",
                        to="civilian.legalmatter",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="generateddocument",
            name="matter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="civilian.legalmatter",
            ),
        ),
        migrations.CreateModel(
            name="AppointmentRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_note", models.TextField(blank=True)),
                ("proposed_time", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(default="requested", max_length=30)),
                ("communication_options", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appointment_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lawyer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appointment_requests",
                        to="civilian.lawyer",
                    ),
                ),
                (
                    "matter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appointments",
                        to="civilian.legalmatter",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MatterAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            (
                                "signed_document",
                                "Signed / certified / stamped document",
                            ),
                            ("proof_of_loan", "Proof money was given"),
                            ("borrower_id", "Borrower ID / identity proof"),
                            ("repayment_evidence", "Repayment evidence"),
                            ("collateral_proof", "Collateral proof"),
                            ("message_evidence", "Messages about the loan"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=60,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=180)),
                ("file", models.FileField(upload_to="citizen_matter_uploads/%Y/%m/")),
                ("note", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "matter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="civilian.citizenmatter",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matter_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="MatterPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="USD", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("expected", "Expected"),
                            ("pending", "Pending"),
                            ("part_paid", "Part-paid"),
                            ("paid", "Paid"),
                            ("late", "Late"),
                            ("missed", "Missed"),
                        ],
                        default="expected",
                        max_length=30,
                    ),
                ),
                ("paid_date", models.DateField(blank=True, null=True)),
                (
                    "amount_paid",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "matter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="civilian.citizenmatter",
                    ),
                ),
                (
                    "proof",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="primary_payment_proof",
                        to="civilian.matterattachment",
                    ),
                ),
            ],
            options={
                "ordering": ["due_date", "id"],
            },
        ),
        migrations.AddField(
            model_name="matterattachment",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="receipts",
                to="civilian.matterpayment",
            ),
        ),
        migrations.CreateModel(
            name="PathwayDocumentTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "matter_type",
                    models.CharField(
                        choices=[
                            ("lending_money", "Lending money"),
                            ("debt_recovery", "Debt recovery"),
                            ("lease_agreement", "Lease agreement"),
                            ("affidavit", "Affidavit / statement"),
                        ],
                        default="lending_money",
                        max_length=80,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("loan_agreement", "Loan Agreement"),
                            ("acknowledgement_of_debt", "Acknowledgement of Debt"),
                            ("repayment_plan", "Repayment Plan"),
                            ("demand_letter", "Demand Letter"),
                        ],
                        default="loan_agreement",
                        max_length=80,
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("description", models.TextField(blank=True)),
                (
                    "template_file",
                    models.FileField(
                        blank=True, null=True, upload_to="pathway_templates/%Y/%m/"
                    ),
                ),
                ("extracted_text", models.TextField(blank=True)),
                ("support_note", models.TextField(blank=True)),
                ("requires_practitioner_review", models.BooleanField(default=False)),
                ("requires_certification_or_stamp", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("version", models.PositiveIntegerField(default=1)),
                ("last_reviewed_by", models.CharField(blank=True, max_length=160)),
                ("review_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["matter_type", "document_type", "-active", "-version"],
                "indexes": [
                    models.Index(
                        fields=["matter_type", "document_type", "active"],
                        name="civilian_pa_matter__cf5e23_idx",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="citizenmatter",
            name="document_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="civilian.pathwaydocumenttemplate",
            ),
        ),
        migrations.CreateModel(
            name="SupportResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=180)),
                ("resource_type", models.CharField(blank=True, max_length=40)),
                ("city", models.CharField(blank=True, max_length=80)),
                ("province", models.CharField(blank=True, max_length=80)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("phone", models.CharField(blank=True, max_length=80)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("notes", models.TextField(blank=True)),
                ("keywords", models.JSONField(blank=True, default=list)),
                ("verified", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("source_note", models.CharField(blank=True, max_length=255)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["resource_type", "city", "active"],
                        name="civilian_su_resourc_95fc67_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="lawyer",
            index=models.Index(
                fields=["city", "verified", "is_active"],
                name="civilian_la_city_8331c8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="legalmatter",
            index=models.Index(
                fields=["status", "issue_type", "updated_at"],
                name="civilian_le_status_444f29_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="matterattachment",
            index=models.Index(
                fields=["matter", "category", "uploaded_at"],
                name="civilian_ma_matter__f460ea_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="citizenmatter",
            index=models.Index(
                fields=["matter_type", "status", "updated_at"],
                name="civilian_ci_matter__f4659d_idx",
            ),
        ),
    ]
